server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SWM-IDLE/config-repository.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: master
        bootstrap: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, beans

